### ISSUE TITLE
Remote branch checkout copies local reference.

### ISSUE THREAD

**Issue by Nageswari-droid** [neel1996/gitconvex#110]
Checking out remote branches creates a new local branch instead of checking out the actual remote branch.

Example,

Commit head in v2.0.0

![commitv2 0 0](https://user-images.githubusercontent.com/65342122/100270138-a1637780-2f7d-11eb-8e4d-221be4f6c4ea.PNG)

Commit head in v1.1.4

![commitv1 1 4](https://user-images.githubusercontent.com/65342122/100270215-ba6c2880-2f7d-11eb-89fe-4074098115d2.PNG)

**Comment by neel1996** [comment]
@Nageswari-droid fix delivered - https://github.com/neel1996/gitconvex/commit/d4701801bc85de59201d17d88b107812d2bd59ed
