### ISSUE TITLE
Already up to date message is not shown in the pull from remote section.

### ISSUE THREAD

**Issue by Nageswari-droid** [neel1996/gitconvex#111]
![pullFromRemoteAlready](https://user-images.githubusercontent.com/65342122/100270369-f901e300-2f7d-11eb-9984-d83d5047fa16.PNG)

**Comment by neel1996** [comment]
@Nageswari-droid fix delivered - https://github.com/neel1996/gitconvex/commit/d4701801bc85de59201d17d88b107812d2bd59ed
