### ISSUE TITLE
Branch checkout fails in repo menu

### ISSUE THREAD

**Issue by Nageswari-droid** [neel1996/gitconvex#120]
**Describe the bug**
Branch switching is not working from `Repository` section drop down 

**To Reproduce**

1. Go to 'http://localhost:9001/dashboard/repository'
2. Click on 'Branch dropdown list'

**Expected behavior**
To checkout to the changed branch 

**Screenshots**
![image](https://user-images.githubusercontent.com/65342122/102693140-5bc56200-423e-11eb-9a18-b85a45873efb.png)

**Command Line Logs**
Gitconvex displays logs in the command line. Please paste the error logs below

```
{"errors":[{"message":"Cannot query field \"setBranch\" on type \"Mutation\". Did you mean \"addBranch\", \"deleteBranch\", or \"checkoutBranch\"?","locations":[{"line":3,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}],"data":null}
```

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [2.0.0]

**Issue Type**
>mark with [x] to select the check box

- [x] UI Issue
- [ ] Performance Issue
- [x] Feature Breaking Issue
- [ ] Security Issue

**Severity**
>mark with [x] to select the check box

- [ ] Critical (The application crashes / breaks completely)
- [x] High (Blocks you from performing an critical operation)
- [ ] Moderate (Bearable or Manageable issue) 
- [ ] Low (Something is not right, but the impact is minimal)

**Comment by neel1996** [comment]
@Nageswari-droid fix delivered, please test and update
