### ISSUE TITLE
Available Branches bug in new git repos

### ISSUE THREAD

**Issue by Nageswari-droid** [neel1996/gitconvex#121]
**Describe the bug**
Available Branches displays **Repo Head is NIL** in repos with nil commit.

**To Reproduce**
1. Go to repo dashboard
2. See error in Available Branches

**Expected behavior**
Displays repo Head is Nil

**Screenshots**

![NewBranch](https://user-images.githubusercontent.com/65342122/103177964-d0cf1200-48a4-11eb-8636-e532a2074339.PNG)

**Command Line Logs**
Gitconvex displays logs in the command line. Please paste the error logs below

```
Repo head is invalid -> reference not found
2020/12/27 22:55:08 ERROR: Repo has no logs -> reference not found
2020/12/27 22:55:08 ERROR: Repo head is invalid -> reference not found

```

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome
 - Version : 2.0.0

**Issue Type**
>mark with [x] to select the check box

- [x] UI Issue
- [ ] Performance Issue
- [x] Feature Breaking Issue
- [ ] Security Issue

**Severity**
>mark with [x] to select the check box

- [ ] Critical (The application crashes / breaks completely)
- [x] High (Blocks you from performing an critical operation)
- [ ] Moderate (Bearable or Manageable issue) 
- [ ] Low (Something is not right, but the impact is minimal)

**Comment by neel1996** [comment]
@Nageswari-droid Fix deployed.
