### ISSUE TITLE
Icon display error in file explorer section.

### ISSUE THREAD

**Issue by Nageswari-droid** [neel1996/gitconvex#122]
**Describe the bug**
Programming language based icon bug in File explorer section

**To Reproduce**
1. Go to 'Repo dashboard'
2. See error in file explorer section

**Expected behavior**
Icon should be visible based on the language.

**Screenshots**
![iconErr](https://user-images.githubusercontent.com/65342122/103372625-7d550200-4af8-11eb-9dd9-49715fb50940.PNG)

**Command Line Logs**
UI error

**Desktop (please complete the following information):**
 - OS : Windows
 - Browser : Chrome
 - Version : v2.0.1

**Issue Type**
>mark with [x] to select the check box

- [x] UI Issue
- [ ] Performance Issue
- [ ] Feature Breaking Issue
- [ ] Security Issue

**Severity**
>mark with [x] to select the check box

- [ ] Critical (The application crashes / breaks completely)
- [ ] High (Blocks you from performing an critical operation)
- [x] Moderate (Bearable or Manageable issue) 
- [ ] Low (Something is not right, but the impact is minimal)

**Comment by neel1996** [comment]
@Nageswari-droid Fix pushed as part of ef8bf0a

**Comment by neel1996** [comment]
closing issue as the fix has been pushed
