### ISSUE TITLE
Repo rename error

### ISSUE THREAD

**Issue by Nageswari-droid** [neel1996/gitconvex#136]
**Describe the bug**
Failed to validate before saving repo name. If user didn't enter new name then blank space is saved as a new name.

**To Reproduce**
1. Go to 'Settings -> Saved repos'
2. Click on 'Edit button'
3. Save without entering new name.
4. See error (blank space in repo name column)

**Expected behavior**
Validate whether the name is provided or not

**Screenshots**

![repoRenameValidation](https://user-images.githubusercontent.com/65342122/105029027-cead3d00-5a77-11eb-9c5a-6bfda0eda70c.PNG)

**Desktop (please complete the following information):**
 - OS : Windows
 - Browser : Chrome
 - Version : v2.0.1

**Issue Type**
>mark with [x] to select the check box

- [X] UI Issue
- [ ] Performance Issue
- [ ] Feature Breaking Issue
- [ ] Security Issue

**Severity**
>mark with [x] to select the check box

- [ ] Critical (The application crashes / breaks completely)
- [ ] High (Blocks you from performing a critical operation)
- [X] Moderate (Bearable or Manageable issue) 
- [ ] Low (Something is not right, but the impact is minimal)

**Comment by neel1996** [comment]
@Nageswari-droid bug fix has been delivered. Re-test and close the issue
