### ISSUE TITLE
Cloned repo directory issue

### ISSUE THREAD

**Issue by Nageswari-droid** [neel1996/gitconvex#137]
**Describe the bug**
Cloned repo directory is appended incorrectly.

**To Reproduce**
1. Go to "Add new repo"
2. Click on "Clone from remote"
3. See error in cloned repo card

**Expected behavior**
Directory path should be appended

**Desktop (please complete the following information):**
 - OS : Windows
 - Browser : Chrome
 - Version : v2.0.1

**Issue Type**
>mark with [x] to select the check box

- [X] UI Issue
- [X] Performance Issue
- [X] Feature Breaking Issue
- [ ] Security Issue

**Severity**
>mark with [x] to select the check box

- [ ] Critical (The application crashes / breaks completely)
- [X] High (Blocks you from performing a critical operation)
- [ ] Moderate (Bearable or Manageable issue) 
- [ ] Low (Something is not right, but the impact is minimal)

**Comment by neel1996** [comment]
commit 809c5fb5b6aa1a35795eb2acf9f4741ca27d1a9c resolves this bug. Marking as closed
