### ISSUE TITLE
Push operation failed

### ISSUE THREAD

**Issue by Nageswari-droid** [neel1996/gitconvex#141]
**Describe the bug**
"No commits to push" message shows when the remote is deleted even if there are unpushed changes. 

**To Reproduce**
1. Go to repositories and make any commit
2. Go to dashboard, delete a remote.
3. Go to repositories.
4. Click on push to remote

**Expected behavior**
Unpushed changes has to be pushed. 

**Desktop (please complete the following information):**
 - OS : Windows
 - Browser : Chrome
 - Version : v2.1.0

**Issue Type**
>mark with [x] to select the check box

- [ ] UI Issue
- [x] Performance Issue
- [ ] Feature Breaking Issue
- [ ] Security Issue

**Severity**
>mark with [x] to select the check box

- [ ] Critical (The application crashes / breaks completely)
- [x] High (Blocks you from performing a critical operation)
- [ ] Moderate (Bearable or Manageable issue) 
- [ ] Low (Something is not right, but the impact is minimal)

**Comment by neel1996** [comment]
@Nageswari-droid After deleting a remote, the remote reference of the remote branch will be missing. To resolve this, perform a pull to sync the local and the remote branch, then try to push the changes
