### ISSUE TITLE
Installation via brew produce: "Errno::EISDIR: Is a directory - read"

### ISSUE THREAD

**Issue by maks1m** [neel1996/gitconvex#158]
If I try to install gitconvex via brew I get such error: `Errno::EISDIR: Is a directory - read`

1. Go to macOS terminal app
2. Enter command: `brew install itassistors/taps/gitconvex`

Terminal log:
```
❯ brew install itassistors/taps/gitconvex
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 46 formulae.
==> Renamed Formulae
badtouch -> authoscope
==> Updated Casks
Updated 34 casks.

==> Installing gitconvex from itassistors/taps
==> Downloading https://github.com/neel1996/gitconvex/releases/download/2.1.1/gitconvex-v2.1.1-brew.tar.gz
Already downloaded: /Users/maks/Library/Caches/Homebrew/downloads/dc3717885ae50c657269889fdd42c2e4cc27145b1bab98cea263734e52ff1590--gitconvex-v2.1.1-brew.tar.gz
Error: An exception occurred within a child process:
  Errno::EISDIR: Is a directory - read
```

 - OS: macOS 11.4
 - brew 3.1.9
 - zsh 5.8 (x86_64-apple-darwin20.1.0)

**Severity**
- [ x] Critical (The application crashes / breaks completely)
- [ ] High (Blocks you from performing a critical operation)
- [ ] Moderate (Bearable or Manageable issue) 
- [ ] Low (Something is not right, but the impact is minimal)

**Comment by neel1996** [comment]
The change which broke the Tap has been reverted back
