### ISSUE TITLE
Search bar in branch switching module is required

### ISSUE THREAD

**Issue by Nageswari-droid** [neel1996/gitconvex#85]
Sample,

![searchBar](https://user-images.githubusercontent.com/65342122/90962859-d40a5980-e4d0-11ea-84b7-395f101bd1de.PNG)

**Comment by aravinve** [comment]
@neel1996 
![image](https://user-images.githubusercontent.com/43500365/99893273-d9866400-2cb8-11eb-9ab2-8fe29822a1b1.png)

Is this the target component for search impl?

**Comment by neel1996** [comment]
@aravinve the target component is the drop down attached above and also the BranchListComponent which lists all the branches from the repo

**Comment by aravinve** [comment]
https://github.com/neel1996/gitconvex-ui/pull/84

**Comment by aravinve** [comment]
@neel1996 Can this issue be closed?
